AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CF for serverless Cerberus POC
Resources:
  JavaLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: >-
         com.fieldju.cerberus.IamPrincipalAuthHandler::handle
      Runtime: java8
      Description: Java Lambda Function
      MemorySize: 512
      Timeout: 300
      CodeUri: @@CODE_URI@@
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          ROLE_NAME: !Ref LambdaRole
          ACCOUNT_ID: !Ref AWS::AccountId
          REGION: !Ref AWS::Region
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /v2/auth/iam-principal
            Method: POST
  LambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "allow-lambda-to-use-logs-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

Outputs:
  BaseApiUrl:
    Description: The base url for the API
    Value: !Join
      - ''
      - - https://
        - !Ref ServerlessRestApi
        - '.execute-api.'
        - !Ref 'AWS::Region'
        - '.amazonaws.com/Prod'